checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        docker: true
      dependencies:
        override:
          - docker compose build && docker compose run --rm php82 vendor/bin/phpunit

      tests:
        override:
          - command: docker compose run --rm php82 vendor/bin/phpunit --coverage-clover coverage.xml
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
