checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        docker: true
      dependencies:
        override:
          - make build
          - make test v=81

      tests:
        override:
          - command: make build && make coverage
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
