checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        docker: true
      dependencies:
        override:
          - cd tests && docker-compose build && docker-compose run --rm php82 vendor/bin/phpunit

      tests:
        override:
          - command: cd tests && docker-compose run --rm php82 vendor/bin/phpunit --coverage-clover tests/runtime/coverage.xml
            on_node: 1
            coverage:
              file: tests/runtime/coverage.xml
              format: php-clover
