#!/usr/bin/env php
<?php

use PhpAmqpLib\Connection\AMQPStreamConnection;
use Psr\Log\NullLogger;
use Yiisoft\EventDispatcher\Dispatcher\Dispatcher;
use Yiisoft\EventDispatcher\Provider\ListenerCollection;
use Yiisoft\EventDispatcher\Provider\Provider;
use Yiisoft\Injector\Injector;
use Yiisoft\Queue\Message\JsonMessageSerializer;
use Yiisoft\Queue\Middleware\MiddlewareDispatcher;
use Yiisoft\Queue\Middleware\MiddlewareFactory;
use Yiisoft\Queue\QueueFactoryInterface;
use Yiisoft\Test\Support\Container\SimpleContainer;
use Yiisoft\Yii\Console\Application;
use Yiisoft\Queue\AMQP\Adapter;
use Yiisoft\Queue\AMQP\QueueProvider;
use Yiisoft\Queue\AMQP\Settings\Queue as QueueSettings;
use Yiisoft\Queue\Cli\SignalLoop;
use Yiisoft\Queue\Command\ListenCommand;
use Yiisoft\Queue\Command\RunCommand;
use Yiisoft\Queue\Middleware\CallableFactory;
use Yiisoft\Queue\Queue;
use Yiisoft\Queue\QueueFactory;

require_once dirname(__DIR__) . '/vendor/autoload.php';

$logger = new NullLogger();
$container = new SimpleContainer([]);
$injector = new Injector($container);
$callableFactory = new CallableFactory($container);
$worker = new \Yiisoft\Queue\Worker\Worker(
    $logger,
    new Dispatcher(new Provider(new ListenerCollection())),
    $container,
    new MiddlewareDispatcher(new MiddlewareFactory($container, $callableFactory)),
    new MiddlewareDispatcher(new MiddlewareFactory($container, $callableFactory), []),
);
$loop = new SignalLoop();
$pushMiddlewareDispatcher = new MiddlewareDispatcher(new MiddlewareFactory($container, $callableFactory));
$adapter = new Adapter(
    new QueueProvider(
        new AMQPStreamConnection(
            getenv('RABBITMQ_HOST'),
            getenv('RABBITMQ_PORT'),
            getenv('RABBITMQ_USER'),
            getenv('RABBITMQ_PASSWORD'),
        ),
        new QueueSettings(),
    ),
    new JsonMessageSerializer(),
    $loop,
);
$queue = new Queue(
    $worker,
    $loop,
    $logger,
    $pushMiddlewareDispatcher,
    $adapter,
);
$queueFactory = new QueueFactory(
    [],
    $queue,
    $container,
    $callableFactory,
    $injector,
);

$application = new Application();
$application->add(new ListenCommand($queueFactory));
$application->add(new RunCommand($queueFactory, [QueueFactoryInterface::DEFAULT_CHANNEL_NAME]));

$application->run();
