on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

name: bechmark

jobs:
  phpbench:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 81
          - 82
          - 83
          - 84

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if we need to create a baseline for a PR
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.ref }}" != "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            echo "WITH_BENCH_BASELINE=1" >> $GITHUB_ENV
          else
            echo "WITH_BENCH_BASELINE=0" >> $GITHUB_ENV
          fi

      - name: "Baseline creation: Checkout default branch."
        uses: actions/checkout@v4
        if: ${{ env.WITH_BENCH_BASELINE == '1' }}
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Build
        if: ${{ env.WITH_BENCH_BASELINE == '1' }}
        working-directory: ./tests
        run: docker compose build php${{ matrix.php }}

      - name: "Baseline creation: Run PhpBench."
        if: ${{ env.WITH_BENCH_BASELINE == '1' }}
        run: docker compose run --rm php${{ matrix.php }} php vendor/bin/phpbench run --report='aggregate' --tag=default
        working-directory: default

      - name: "Run PhpBench."
        working-directory: ./tests
        run: |
          if [ "${{ env.WITH_BENCH_BASELINE }}" == '1' ]; then
            docker compose run --rm php${{ matrix.php }} php vendor/bin/phpbench run --report='aggregate' --ref=default --assert="mode(variant.time.avg) <= mode(baseline.time.avg) +/- 5%" > phpbench.log
          else
            docker compose run --rm php${{ matrix.php }} php vendor/bin/phpbench run --report='aggregate' > phpbench.log
          fi
