on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

name: bechmark

jobs:
  phpbench:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 81
          - 82
          - 83
          - 84

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: ./tests
        run: docker compose build php${{ matrix.php }}

      - name: "Run PhpBench."
        working-directory: ./tests
        run: docker compose run --rm -e XDEBUG_MODE=off php${{ matrix.php }} php vendor/bin/phpbench run --report='aggregate' > phpbench.log
