on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

permissions:
  contents: read
jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 81, 82, 83, 84 ]
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
        with:
          persist-credentials: false
      - name: Build
        working-directory: ./tests
        run: docker compose build
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        working-directory: ./tests
        run: docker compose run --rm php${{ matrix.php }} vendor/bin/phpunit --colors=always -v --debug
