name: build

on:
  pull_request:
    paths: &paths
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 81, 82, 83, 84 ]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build
        working-directory: ./tests
        run: docker compose build
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        working-directory: ./tests
        run: docker compose run --rm php${{ matrix.php }} vendor/bin/phpunit --colors=always -v --debug
