on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 80, 81, 82 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        working-directory: ./tests
        run: docker compose build
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        working-directory: ./tests
        run: docker compose run --rm php${{ matrix.php }} vendor/bin/phpunit --colors=always -v --debug
